import React from 'react';
import { Box, Typography, alpha, useTheme } from '@mui/material';
import {
  Add, SwapHoriz, PersonAdd, ChatBubble, CheckCircle, Edit, PriorityHigh,
  CalendarToday, Visibility, SmartToy, Assignment, Label,
} from '@mui/icons-material';
import { formatRelativeTime } from '../../utils/formatters';

const ACTION_CONFIG = {
  created: { icon: Add, color: 'info', label: 'created this task' },
  updated: { icon: Edit, color: 'default', label: 'updated task details' },
  status_changed: { icon: SwapHoriz, color: 'warning', label: 'changed status' },
  assigned: { icon: PersonAdd, color: 'primary', label: 'assigned task' },
  reassigned: { icon: PersonAdd, color: 'primary', label: 'reassigned task' },
  priority_changed: { icon: PriorityHigh, color: 'warning', label: 'changed priority' },
  comment_added: { icon: ChatBubble, color: 'info', label: 'added a comment' },
  checklist_updated: { icon: CheckCircle, color: 'success', label: 'updated checklist' },
  due_date_changed: { icon: CalendarToday, color: 'warning', label: 'changed due date' },
  watcher_added: { icon: Visibility, color: 'default', label: 'added a watcher' },
  watcher_removed: { icon: Visibility, color: 'default', label: 'removed a watcher' },
  escalated: { icon: PriorityHigh, color: 'error', label: 'task was escalated' },
  sub_task_added: { icon: Assignment, color: 'info', label: 'added a sub-task' },
  tag_added: { icon: Label, color: 'default', label: 'added a tag' },
  tag_removed: { icon: Label, color: 'default', label: 'removed a tag' },
  template_applied: { icon: Assignment, color: 'primary', label: 'applied a template' },
  auto_generated: { icon: SmartToy, color: 'info', label: 'auto-generated by system' },
  bulk_updated: { icon: SwapHoriz, color: 'default', label: 'bulk updated' },
};

const getDescription = (entry) => {
  const config = ACTION_CONFIG[entry.action] || { label: entry.action };

  if (entry.action === 'status_changed' && entry.previousValue && entry.newValue) {
    return `changed status from ${entry.previousValue} to ${entry.newValue}`;
  }
  if (entry.action === 'priority_changed' && entry.previousValue && entry.newValue) {
    return `changed priority from ${entry.previousValue} to ${entry.newValue}`;
  }
  return config.label;
};

const ActivityTimeline = ({ activityLog = [] }) => {
  const theme = useTheme();

  if (!activityLog || activityLog.length === 0) {
    return (
      <Typography variant="body2" color="text.disabled" sx={{ py: 2, textAlign: 'center' }}>
        No activity yet
      </Typography>
    );
  }

  return (
    <Box sx={{ position: 'relative', pl: 3 }}>
      {/* Vertical line */}
      <Box
        sx={{
          position: 'absolute',
          left: 11,
          top: 4,
          bottom: 4,
          width: 2,
          bgcolor: alpha(theme.palette.divider, 0.5),
          borderRadius: 1,
        }}
      />

      {activityLog.map((entry, idx) => {
        const config = ACTION_CONFIG[entry.action] || { icon: Edit, color: 'default' };
        const IconComp = config.icon;
        const colorKey = config.color === 'default' ? 'grey' : config.color;
        const iconColor = theme.palette[colorKey]?.main || theme.palette.grey[500];

        return (
          <Box key={entry._id || idx} sx={{ display: 'flex', alignItems: 'flex-start', gap: 1.5, mb: 2, position: 'relative' }}>
            {/* Icon dot */}
            <Box
              sx={{
                position: 'absolute',
                left: -24,
                width: 22,
                height: 22,
                borderRadius: '50%',
                bgcolor: alpha(iconColor, 0.1),
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                border: `2px solid ${theme.palette.background.paper}`,
              }}
            >
              <IconComp sx={{ fontSize: 12, color: iconColor }} />
            </Box>

            {/* Content */}
            <Box sx={{ flex: 1, minWidth: 0 }}>
              <Typography variant="body2" color="text.primary">
                {getDescription(entry)}
              </Typography>
              <Typography variant="caption" color="text.secondary">
                {formatRelativeTime(entry.performedAt)}
              </Typography>
            </Box>
          </Box>
        );
      })}
    </Box>
  );
};

export default ActivityTimeline;
