// File: src/components/ai/AIScheduledPlaceholder.jsx
// Description: SP5 — friendly "Available at <date>" placeholder for digest
//   surfaces that haven't been generated by the cron yet. Per spec §4.3.

import React from 'react';
import { Box, Typography, Paper } from '@mui/material';
import { Schedule, AutoAwesome } from '@mui/icons-material';

const AIScheduledPlaceholder = ({ surface = 'weekly_digest', nextRunAt, copy }) => {
  const formatted = nextRunAt
    ? new Date(nextRunAt).toLocaleString(undefined, {
        weekday: 'short',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })
    : 'soon';

  const heading = surface === 'monthly_digest' ? 'Your monthly digest is on the way' : 'Your next digest is on the way';
  const body =
    copy ||
    `We compile this digest automatically every ${surface === 'monthly_digest' ? 'month' : 'Sunday at 22:00 IST'}. ` +
      `Your next one will be available ${formatted}.`;

  return (
    <Paper variant="outlined" sx={{ p: 3, textAlign: 'center', borderStyle: 'dashed' }}>
      <Box sx={{ position: 'relative', display: 'inline-flex', mb: 1.5 }}>
        <AutoAwesome sx={{ fontSize: 36, color: 'primary.light' }} />
        <Schedule sx={{ fontSize: 18, position: 'absolute', right: -4, bottom: -2, color: 'text.secondary' }} />
      </Box>
      <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>{heading}</Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5, maxWidth: 520, mx: 'auto' }}>
        {body}
      </Typography>
    </Paper>
  );
};

export default AIScheduledPlaceholder;
