import React, { useState, useEffect } from 'react';
import {
  Box, Grid, ToggleButtonGroup, ToggleButton, useTheme,
} from '@mui/material';
import {
  CheckCircle, Schedule, TrendingUp, BarChart as BarChartIcon,
} from '@mui/icons-material';
import { useSnackbar } from 'notistack';
import {
  PieChart, Pie, Cell, BarChart, Bar, LineChart, Line,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend,
} from 'recharts';
import { tasksAPI } from '../../services/api';
import { PageHeader, KPICard, ChartCard } from '../../components/common';
import { CardGridSkeleton } from '../../components/common/LoadingSkeleton';
import { CHART_COLORS } from '../../constants/statusConfig';

const PERIODS = [
  { value: 30, label: '30 days' },
  { value: 60, label: '60 days' },
  { value: 90, label: '90 days' },
];

const TaskAnalyticsPage = () => {
  const theme = useTheme();
  const { enqueueSnackbar } = useSnackbar();

  const [loading, setLoading] = useState(true);
  const [data, setData] = useState(null);
  const [period, setPeriod] = useState(30);

  useEffect(() => {
    let cancelled = false;
    const fetchAnalytics = async () => {
      setLoading(true);
      try {
        const res = await tasksAPI.getAnalytics({ period });
        if (!cancelled) setData(res.data?.data || res.data || {});
      } catch {
        if (!cancelled) enqueueSnackbar('Failed to load analytics', { variant: 'error' });
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    fetchAnalytics();
    return () => { cancelled = true; };
  }, [period, enqueueSnackbar]);

  if (loading) {
    return (
      <Box>
        <PageHeader title="Task Analytics" loading />
        <CardGridSkeleton />
      </Box>
    );
  }

  const analytics = data?.analytics || {};

  // KPI values from nested arrays
  const completionRateVal = analytics.completionRate?.[0]?.rate;
  const totalTasksVal = analytics.completionRate?.[0]?.total
    || (analytics.statusDistribution || []).reduce((s, d) => s + d.count, 0);
  const avgResolutionVal = analytics.avgResolutionTime?.[0]?.avgHours != null
    ? Math.abs(analytics.avgResolutionTime[0].avgHours).toFixed(0) : null;
  const slaComplianceVal = analytics.slaCompliance?.[0]?.complianceRate;

  // Distributions — API returns { _id, count }; map to named keys for charts
  const statusDist = (analytics.statusDistribution || []).map((d) => ({ status: d._id, count: d.count }));
  const priorityDist = (analytics.priorityDistribution || []).map((d) => ({ priority: d._id, count: d.count }));
  const categoryDist = (analytics.categoryDistribution || []).map((d) => ({ category: d._id, count: d.count }));

  // Trend data — API returns { _id: { year, week }, created, completed }
  const trendData = (analytics.createdVsCompleted || []).map((d) => ({
    date: `W${d._id?.week}`,
    created: d.created,
    completed: d.completed,
  }));

  // Team workload — API returns { _id, totalTasks, overdueTasks, user }
  const workloadData = (analytics.teamWorkload || []).map((d) => ({
    name: `${d.user?.firstName || ''} ${d.user?.lastName || ''}`.trim(),
    total: d.totalTasks,
    overdue: d.overdueTasks,
  }));

  const overdueAging = analytics.overdueAging || [];
  const autoBreakdown = analytics.autoGeneratedBreakdown || [];

  return (
    <Box>
      <PageHeader
        title="Task Analytics"
        subtitle={`Last ${period} days`}
        actions={
          <ToggleButtonGroup
            value={period}
            exclusive
            onChange={(_, v) => v && setPeriod(v)}
            size="small"
          >
            {PERIODS.map((p) => (
              <ToggleButton key={p.value} value={p.value}>{p.label}</ToggleButton>
            ))}
          </ToggleButtonGroup>
        }
      />

      {/* KPI Row */}
      <Grid container spacing={2} sx={{ mb: 3 }}>
        <Grid item xs={6} sm={3}>
          <KPICard
            title="Completion Rate"
            value={completionRateVal != null ? `${completionRateVal}%` : '-'}
            icon={CheckCircle}
            color="success"
          />
        </Grid>
        <Grid item xs={6} sm={3}>
          <KPICard
            title="Avg Resolution"
            value={avgResolutionVal != null ? `${avgResolutionVal}h` : '-'}
            icon={Schedule}
            color="info"
          />
        </Grid>
        <Grid item xs={6} sm={3}>
          <KPICard
            title="SLA Compliance"
            value={slaComplianceVal != null ? `${slaComplianceVal}%` : '-'}
            icon={TrendingUp}
            color="primary"
          />
        </Grid>
        <Grid item xs={6} sm={3}>
          <KPICard
            title="Total Tasks"
            value={totalTasksVal || 0}
            icon={BarChartIcon}
            color="warning"
          />
        </Grid>
      </Grid>

      {/* Charts */}
      <Grid container spacing={3}>
        {/* Status Distribution */}
        <Grid item xs={12} md={6}>
          <ChartCard title="Status Distribution">
            <ResponsiveContainer width="100%" height={280}>
              <PieChart>
                <Pie data={statusDist} dataKey="count" nameKey="status" cx="50%" cy="50%" outerRadius={90} label={({ status }) => status}>
                  {statusDist.map((_, idx) => (
                    <Cell key={idx} fill={CHART_COLORS[idx % CHART_COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </ChartCard>
        </Grid>

        {/* Priority Distribution */}
        <Grid item xs={12} md={6}>
          <ChartCard title="Priority Distribution">
            <ResponsiveContainer width="100%" height={280}>
              <BarChart data={priorityDist}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="priority" tick={{ fontSize: 12 }} />
                <YAxis />
                <Tooltip />
                <Bar dataKey="count" fill={theme.palette.primary.main} radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </ChartCard>
        </Grid>

        {/* Category Pie */}
        <Grid item xs={12} md={6}>
          <ChartCard title="By Category">
            <ResponsiveContainer width="100%" height={280}>
              <PieChart>
                <Pie data={categoryDist} dataKey="count" nameKey="category" cx="50%" cy="50%" outerRadius={90} label={({ category }) => category}>
                  {categoryDist.map((_, idx) => (
                    <Cell key={idx} fill={CHART_COLORS[idx % CHART_COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </ChartCard>
        </Grid>

        {/* Created vs Completed trend */}
        <Grid item xs={12} md={6}>
          <ChartCard title="Created vs Completed">
            <ResponsiveContainer width="100%" height={280}>
              <LineChart data={trendData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="date" />
                <YAxis />
                <Tooltip />
                <Legend />
                <Line type="monotone" dataKey="created" stroke={theme.palette.info.main} strokeWidth={2} />
                <Line type="monotone" dataKey="completed" stroke={theme.palette.success.main} strokeWidth={2} />
              </LineChart>
            </ResponsiveContainer>
          </ChartCard>
        </Grid>

        {/* Team Workload */}
        {workloadData.length > 0 && (
          <Grid item xs={12}>
            <ChartCard title="Team Workload">
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={workloadData} layout="vertical">
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis type="number" />
                  <YAxis dataKey="name" type="category" width={120} />
                  <Tooltip />
                  <Legend />
                  <Bar dataKey="total" fill={CHART_COLORS[0]} name="Total Tasks" radius={[0, 4, 4, 0]} />
                  <Bar dataKey="overdue" fill="#e53935" name="Overdue" radius={[0, 4, 4, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </ChartCard>
          </Grid>
        )}

        {/* Overdue Aging */}
        {overdueAging.length > 0 && (
          <Grid item xs={12} md={6}>
            <ChartCard title="Overdue Aging">
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={overdueAging.map((d) => ({
                  bucket: d._id === 0 ? '0-7 days' : d._id === 7 ? '7-14 days' : d._id === 14 ? '14-30 days' : '30+ days',
                  count: d.count,
                }))}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="bucket" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="count" fill="#e53935" radius={[4, 4, 0, 0]} name="Overdue Tasks" />
                </BarChart>
              </ResponsiveContainer>
            </ChartCard>
          </Grid>
        )}

        {/* Auto-Generated Breakdown */}
        {autoBreakdown.length > 0 && (
          <Grid item xs={12} md={6}>
            <ChartCard title="Auto-Generated Tasks by Trigger">
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={autoBreakdown.map((d) => ({
                  trigger: (d._id || '').replace(/_/g, ' '),
                  count: d.count,
                }))}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="trigger" />
                  <YAxis />
                  <Tooltip />
                  <Bar dataKey="count" fill={theme.palette.info.main} radius={[4, 4, 0, 0]} name="Tasks" />
                </BarChart>
              </ResponsiveContainer>
            </ChartCard>
          </Grid>
        )}
      </Grid>
    </Box>
  );
};

export default TaskAnalyticsPage;
